site_name: United States Aviation

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.tooltips
    - navigation.footer
  logo: images/USAAw.png
  icon:
    repo: fontawesome/brands/github
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/unitedstatesaviation
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: black
      accent: light blue

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: light blue

plugins:
  - search
  - awesome-nav:
      filename: .nav.yml 
      logs: 
        nav_override: warning
        root_title: warning
        root_hide: warning
        no_matches: warning
  - tags:
      enabled: false
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocs-pdf
  - blog

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true

repo_url: https://github.com/unitedstatesaviation/sops
repo_name: unitedstatesaviation/sops

copyright: This website should be used for simulation purposes only. United States Aviation is not affiliated with the FAA or any government entity. <br>United States Aviation Website © 2025 by United States Aviation is licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/unitedstatesaviation
        name: GitHub
      - icon: material/email
        link: mailto:info@unitedstatesaviation.us
        name: Email
      - icon: simple/moodle
        link: https://srv1049714.hstgr.cloud/login/index.php
        name: Moodle