authors:
  u1201:
    name: Sebastian Kang
    description: USAA Division Director (USAA1)/Honoulu (HCF) ATM
    avatar: https://srv1049714.hstgr.cloud/pluginfile.php/58/user/icon/boost/f1?rev=214
  u1101:
    name: Amalia Kendall
    description: Anchorage (ZAN) ATM
    avatar: https://srv1049714.hstgr.cloud/pluginfile.php/59/user/icon/boost/f1?rev=300