nav:
  - Home: index.md
  - ARTCC SOPs: artccs
  - Home: index.md
  - Track: https://track.unitedstatesaviation.us
  - Connect: https://connect.unitedstatesaviation.us
  - Admin: https://track.unitedstatesaviation.us
  - Data: https://data.unitedstatesaviation.us
  - Network: https://us-aviation.network